# image will be published to ghcr.io/<user>/<name>
name: artemis_ublue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
# base-image: ghcr.io/wayblueorg/hyprland
base-image: ghcr.io/ublue-os/sericea-surface
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://pkg.surfacelinux.com/fedora/linux-surface.repo
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
      - https://copr.fedorainfracloud.org/coprs/blakegardner/xremap/repo/fedora-40/blakegardner-xremap-fedora-40.repo
      - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-40/tofik-nwg-shell-fedora-40.repo
      - https://copr.fedorainfracloud.org/coprs/porras/lisgd/repo/fedora-40/porras-lisgd-fedora-40.repo
    install:
      # Packages For Surface
      # - fprintd
      # - libcamera
      # - libcamera-tools
      # - libcamera-gstreamer
      # - libcamera-ipa
      # - pipewire-plugin-libcamera
      # - kernel-surface
      # - iptsd
      # - libwacom-surface
      # - libwacom-surface-data
      # - surface-secureboot

      # Other Packages
      - alacritty
      - newsboat
      - btop
      - bat
      - eza
      - ripgrep
      - zsh
      - vifm
      - jq
      - aria2
      - wget
      - yt-dlp
      - mullvad-vpn
      - fuse-sshfs
      - mpv
      - qutebrowser
      - speedcrunch
      - bemenu
      - fastfetch
      - distrobox
      - pass
      - fzf
      # - ncmpcpp
      # - mpd
      - feh
      # - NetworkManager-tui
      - xremap-wlroots
      - doas
      - neovim
      - luarocks
      - npm
      - squeekboard
      - waydroid
      - polkit-qt
      - nwg-dock
      - gamemode
      - pinentry-qt
      - lisgd
      - power-profiles-daemon

      - android-file-transfer

      # Fonts
      - google-noto-sans-cjk-fonts
      - google-noto-emoji-fonts
      - google-noto-color-emoji-fonts
    remove:
      # - kernel
      # - kernel-core
      # - kernel-modules
      # - kernel-modules-core
      # - kernel-modules-extra
      # - libwacom
      # - libwacom-data
      - firefox
      - firefox-langpacks
  # Systemd
  - type: systemd
    system:
      enabled:
        - surface-hardware-setup.service
        - xremap.service
        # - flatpak_run_script.timer

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        - com.github.tchx84.Flatseal
        - org.gimp.GIMP
        - org.kde.krita
        - rocks.koreader.KOReader
        - com.discordapp.Discord
        - com.spotify.Client
        - io.github.hrkfdn.ncspot
        - io.github.zen_browser.zen
        - io.freetubeapp.FreeTube
        - com.moonlight_stream.Moonlight
        - org.kde.falkon
        - org.kde.okular
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

